// <auto-generated />
using Demo.API.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Demo.API.Migrations
{
    [DbContext(typeof(CountryInfoContext))]
    partial class CountryInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Demo.API.Tables.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Density")
                        .HasColumnType("int");

                    b.Property<int>("LandArea")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Density = 60,
                            LandArea = 652860,
                            Name = "Afghanistan",
                            Population = 38928346
                        },
                        new
                        {
                            Id = 2,
                            Density = 105,
                            LandArea = 27400,
                            Name = "Albania",
                            Population = 2877797
                        },
                        new
                        {
                            Id = 3,
                            Density = 18,
                            LandArea = 2381740,
                            Name = "Algeria",
                            Population = 43851044
                        });
                });

            modelBuilder.Entity("Demo.API.Tables.OfficialLanguages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("OfficialLanguages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            LanguageName = "Pashto"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            LanguageName = "Dari"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 2,
                            LanguageName = "Albanian"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 3,
                            LanguageName = "Arabic"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 3,
                            LanguageName = "Tamazight"
                        });
                });

            modelBuilder.Entity("Demo.API.Tables.OfficialLanguages", b =>
                {
                    b.HasOne("Demo.API.Tables.Country", "Country")
                        .WithMany("OfficialLanguages")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
